export { default as Studies } from './Studies';
export { default as Undergraduate } from './Undergraduate';
export { default as Msc } from './Msc';
export { default as Phd } from './Phd';
export { default as Courses } from './Courses';
export { default as Course } from './Course';
export { default as NewCourse } from './NewCourse';
export { default as CreateStatement } from './CreateStatement';
export { default as InfoSecMsc } from './Msc/InfoSecMsc';
// export { default as IotMsc } from './Msc/IotMsc';
// export { default as InnovationMsc } from './Msc/InnovationMsc';
// export { default as IcsConversionMsc } from './Msc/IcsConversionMsc';
// export { default as EgovMsc } from './Msc/EgovMsc';
